### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by solnic**
Refs #1255

### CODE REVIEW

**Comment by solnic** [comment]
[Update hanami README](https://trello.com/c/UneSTkPr/343-update-hanami-readme)

**Review by timriley — APPROVED** [review]
Looks good for getting rid of the out-of-date/misleading info 👍🏼 

At some point I might come back for another pass at the high-level description of Hanami, but that can definitely be a task for another PR and another day.

It might be worth having a note about our current versions somewhere in the PR, e.g. saying that view, helpers, assets, model (which is not listed here, oddly) are still in development for 2.0 and will arrive in Q1 2023.

**Comment by solnic** [comment]
@timriley should we (tomorrow) just link to the 2.0 ann post somewhere at the top?

**Comment by timriley** [comment]
@solnic good idea! Can you make a trello card for that? Just so we remember?

**Comment by solnic** [comment]
@timriley https://trello.com/c/bbgftHPt

**Pull request merged**
