### PR TITLE
Serve only existing assets with Rack::Static

### PR DESCRIPTION
**Pull request by kaikuchn**
Closes https://github.com/hanami/hanami/issues/696

### CODE REVIEW

**Comment by kaikuchn** [comment]
Instead of passing an array of folders that exist in the `root` directory into `Rack::Static` we now pass a hash which maps URIs to files as described in the [Rack docs](https://github.com/rack/rack/blob/master/lib/rack/static.rb#L23).
We thereby only trigger the rack fileserver for URIs resolvable to static files, else we delegate to later middlewares to handle the request.

**Comment by AlfonsoUceda** [comment]
@kaikuchn we need a test or tests proving the failing scenario, could you add one? If you don't know how to start, maybe @jodosha could help you to point out what you need for that.

**Comment by kaikuchn** [comment]
Sure, I actually wrote a failing test first. But then I realized that it isn't executed when I run `bundle exec rake test`. I then looked into the README on how to run the test suite and did as explained. However several tests would fail on my local machine.

Any pointers to where I can read up on what I need to do to get the tests on `HEAD` to pass?

**Comment by mereghost** [comment]
@kaikuchn You need a `phantomjs` binary on you `PATH` to make all the tests pass.

Which ones are failing?

**Comment by kaikuchn** [comment]
```
Failed examples:

rspec ./spec/isolation/components/all/component_spec.rb:2 # Components: all loads all
```
Here's a [gist](https://gist.github.com/kaikuchn/c2274d20448748a0e2d22e1cf6d9cbcc) containing all the output from running `./script/ci`

phantomjs is on my path:
```bash
> which phantomjs
/usr/local/bin/phantomjs
> phantomjs --version
2.1.1
```

**Comment by kaikuchn** [comment]
@mereghost or @AlfonsoUceda any ideas what might be wrong?

**Comment by mereghost** [comment]
@kaikuchn =/ I was unable to reproduce, even against your fork.

**Comment by kaikuchn** [comment]
Tracking IO I can see that the generate command never generates anything (at least it does not write to disk!) on my system. I'm on maxOS Sierra 10.12.2.. maybe it doesn't work for OS X?
Anyway I'll just do this on my linux system this weekend and get back to you.
Anyway, thank you for your help but I'll just give up fixing this on my OS X device.

**Comment by jodosha** [comment]
@kaikuchn Can you just please paste here as a diff your test? I'll apply it to this PR.

**Comment by kaikuchn** [comment]
Hey, sorry for not getting back to you guys for weeks!
This [gist](https://gist.github.com/kaikuchn/a42b8efb56bce721b871770be1c79c12) contains a test that might fail on the current master branch's head and pass with my changes. It's hypothetical though.. I've also added this spec to this PR after rebasing onto the current head of hanami/hanami.

**Comment by jodosha** [comment]
@kaikuchn I verified the PR, it works great. Thank you very much! FYI have a look at https://github.com/hanami/hanami/commit/415c8fdbe6800402fabe17f75f00617c0bd9957d to see how I made it to work.

**Comment by kaikuchn** [comment]
Awesome! Thank you for helping out!

**Pull request merged**
