### PR TITLE
Set application to nil by default and throw error if arch is a container

### LINKED ISSUE #584: Destroy command: It doesn't work with app architecture
This command is expected to work:

```shell
bundle exec hanami destroy action home#index
ERROR: "hanami actions" was called with arguments ["home#index"]
Usage: "hanami action APPLICATION_NAME CONTROLLER_NAME#ACTION_NAME"
```

### PR DESCRIPTION
**Pull request by maheshm**
Fixes #584

### CODE REVIEW

**Comment by jodosha** [comment]
@maheshm Thank you for this PR. Can you please provide a test? Thanks.

/cc @cllns

**Comment by maheshm** [comment]
Sure, Will add test @jodosha

**Comment by maheshm** [comment]
Sorry, I was not able to work on this. I will pick it up this week.

**Comment by maheshm** [comment]
Have added just one test that is directly associated with the bug. But lots of tests are missing related to the destroy command. I will raise a separate PR for the rest of the tests. @jodosha @cllns

**Comment by jodosha** [comment]
@maheshm I restarted the build. The error was caused by #598 which is now fixed.
@cllns would you mind to review? Thanks 😄

**Comment by jodosha** [comment]
@maheshm this works fine. Thanks! /cc @cllns

**Pull request merged**
