### PR TITLE
Create simple one file template for hanami model with sqlite adapter

### PR DESCRIPTION
**Pull request by davydovanton**
I created a simple part of https://github.com/hanami/hanami/issues/786. Thanks https://github.com/hanami/hanami/pull/826 for helping with some code.

## Manual testing
```
$ ruby templates/model_sqlite.rb
```

After you'll see something like this:
screenshot 2018-02-20 20 28 29

### CODE REVIEW

**Comment by davydovanton** [comment]
@jodosha I have no idea what the best place for this (thought about community repository too). I think it will be super cool to use one place for all these files. But if you not agree - I can move it to model

**Comment by jodosha** [comment]
@davydovanton I'm fine to keep it here in one place all of these files. Just wanted to double check with you the intent.

**Comment by davydovanton** [comment]
@jodosha I'll merge it to hanami/hanami. If we understand that we need other place for this files we'll move it 👍

**Comment by jodosha** [comment]
@davydovanton I've got two problems here:

### Problem 1

This crashes when ran from the root directory of `hanami/hanami`:

```shell
➜ pwd
/Users/luca/Code/hanami/hanami
➜ ruby templates/model_sqlite.rb
Fetching git://github.com/hanami/model.git
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Using rake 12.3.1
Using bundler 1.16.1
Using concurrent-ruby 1.0.5
Using diff-lcs 1.3
Using dry-configurable 0.7.0
Using dry-container 0.6.0
Using dry-core 0.4.5
Using dry-equalizer 0.2.0
Using dry-initializer 1.4.1
Using dry-logic 0.4.2
Using inflecto 0.0.2
Using dry-types 0.11.1
Using ice_nine 0.11.2
Using dry-struct 0.3.1
Using transproc 1.0.2
Using hanami-utils 1.1.2 (was 1.2.0.rc1)
Using rom-mapper 0.5.1
Using rom 3.3.3
Using rom-repository 1.4.0
Using sequel 4.49.0
Using rom-sql 1.3.5
Using hanami-model 1.1.0 (was 1.2.0.rc1) from git://github.com/hanami/model.git (at master@db03072)
Using rspec-support 3.7.1
Using rspec-core 3.7.1
Using rspec-expectations 3.7.0
Using rspec-mocks 3.7.0
Using rspec 3.7.0
Using sqlite3 1.3.13
Traceback (most recent call last):
	20: from /Users/luca/.gem/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:24:in `block in autorun'
	19: from /Users/luca/.gem/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:38:in `perform_at_exit'
	18: from /Users/luca/.gem/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
	17: from /Users/luca/.gem/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
	16: from /Users/luca/.gem/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:86:in `run'
	15: from /Users/luca/.gem/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:99:in `setup'
	14: from /Users/luca/.gem/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:21:in `configure'
	13: from /Users/luca/.gem/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:111:in `process_options_into'
	12: from /Users/luca/.gem/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:111:in `each'
	11: from /Users/luca/.gem/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:112:in `block in process_options_into'
	10: from /Users/luca/.gem/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1455:in `requires='
	 9: from /Users/luca/.gem/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1455:in `each'
	 8: from /Users/luca/.gem/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1455:in `block in requires='
	 7: from /Users/luca/.gem/ruby/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1455:in `require'
	 6: from /Users/luca/Code/hanami/hanami/spec/spec_helper.rb:27:in `<top (required)>'
	 5: from /Users/luca/Code/hanami/hanami/spec/spec_helper.rb:27:in `require'
	 4: from /Users/luca/Code/hanami/hanami/lib/hanami.rb:8:in `<top (required)>'
	 3: from /Users/luca/Code/hanami/hanami/lib/hanami.rb:10:in `<module:Hanami>'
	 2: from /Users/luca/Code/hanami/hanami/lib/hanami.rb:10:in `require'
	 1: from /Users/luca/Code/hanami/hanami/lib/hanami/frameworks.rb:2:in `<top (required)>'
/Users/luca/Code/hanami/hanami/lib/hanami/frameworks.rb:2:in `require': cannot load such file -- hanami/validations (LoadError)
```

### Problem 2

The script isn't idempotent. The **second time** I run the command again, I get a different error.

```shell
➜ ruby templates/model_sqlite.rb
Fetching git://github.com/hanami/model.git
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Using rake 12.3.1
Using bundler 1.16.1
Using concurrent-ruby 1.0.5
Using diff-lcs 1.3
Using dry-configurable 0.7.0
Using dry-container 0.6.0
Using dry-core 0.4.5
Using dry-equalizer 0.2.0
Using dry-initializer 1.4.1
Using dry-logic 0.4.2
Using inflecto 0.0.2
Using dry-types 0.11.1
Using ice_nine 0.11.2
Using dry-struct 0.3.1
Using transproc 1.0.2
Using hanami-utils 1.1.2 (was 1.2.0.rc1)
Using rom-mapper 0.5.1
Using rom 3.3.3
Using rom-repository 1.4.0
Using sequel 4.49.0
Using rom-sql 1.3.5
Using hanami-model 1.1.0 (was 1.2.0.rc1) from git://github.com/hanami/model.git (at master@db03072)
Using rspec-support 3.7.1
Using rspec-core 3.7.1
Using rspec-expectations 3.7.0
Using rspec-mocks 3.7.0
Using rspec 3.7.0
Using sqlite3 1.3.13
Traceback (most recent call last):
	24: from templates/model_sqlite.rb:41:in `<main>'
	23: from /Users/luca/.gem/ruby/2.5.0/bundler/gems/model-db03072fa29c/lib/hanami/model/migration.rb:27:in `run'
	22: from /Users/luca/.gem/ruby/2.5.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:106:in `apply'
	21: from /Users/luca/.gem/ruby/2.5.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:106:in `instance_eval'
	20: from templates/model_sqlite.rb:27:in `block (2 levels) in <main>'
	19: from /Users/luca/.gem/ruby/2.5.0/gems/sequel-4.49.0/lib/sequel/database/schema_methods.rb:213:in `create_table'
	18: from /Users/luca/.gem/ruby/2.5.0/gems/sequel-4.49.0/lib/sequel/database/schema_methods.rb:697:in `create_table_from_generator'
	17: from /Users/luca/.gem/ruby/2.5.0/gems/sequel-4.49.0/lib/sequel/adapters/sqlite.rb:145:in `execute_ddl'
	16: from /Users/luca/.gem/ruby/2.5.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `synchronize'
	15: from /Users/luca/.gem/ruby/2.5.0/gems/sequel-4.49.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
	14: from /Users/luca/.gem/ruby/2.5.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `block in synchronize'
	13: from /Users/luca/.gem/ruby/2.5.0/gems/sequel-4.49.0/lib/sequel/adapters/sqlite.rb:148:in `block in execute_ddl'
	12: from /Users/luca/.gem/ruby/2.5.0/gems/sequel-4.49.0/lib/sequel/database/query.rb:47:in `execute_ddl'
	11: from /Users/luca/.gem/ruby/2.5.0/gems/sequel-4.49.0/lib/sequel/adapters/sqlite.rb:138:in `execute_dui'
	10: from /Users/luca/.gem/ruby/2.5.0/gems/sequel-4.49.0/lib/sequel/adapters/sqlite.rb:188:in `_execute'
	 9: from /Users/luca/.gem/ruby/2.5.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `synchronize'
	 8: from /Users/luca/.gem/ruby/2.5.0/gems/sequel-4.49.0/lib/sequel/connection_pool/threaded.rb:103:in `hold'
	 7: from /Users/luca/.gem/ruby/2.5.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `block in synchronize'
	 6: from /Users/luca/.gem/ruby/2.5.0/gems/sequel-4.49.0/lib/sequel/adapters/sqlite.rb:200:in `block in _execute'
	 5: from /Users/luca/.gem/ruby/2.5.0/gems/sequel-4.49.0/lib/sequel/database/logging.rb:45:in `log_connection_yield'
	 4: from /Users/luca/.gem/ruby/2.5.0/gems/sequel-4.49.0/lib/sequel/adapters/sqlite.rb:200:in `block (2 levels) in _execute'
	 3: from /Users/luca/.gem/ruby/2.5.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:221:in `execute_batch'
	 2: from /Users/luca/.gem/ruby/2.5.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `prepare'
	 1: from /Users/luca/.gem/ruby/2.5.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `new'
/Users/luca/.gem/ruby/2.5.0/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `initialize': SQLite3::SQLException: table `authors` already exists (Sequel::DatabaseError)
```

This because since the last attempt there was the leftover SQLite3 database:

```shell
➜ git status
On branch develop
Your branch is up to date with 'origin/develop'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	hanami_model_template.db

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by davydovanton** [comment]
nice, I'll fix it. Thanks for update, @jodosha ❤️

**Comment by davydovanton** [comment]
@jodosha done 👍

**Pull request merged**
