### PR TITLE
Add --table-name options to model generator (Issue #823)

### PR DESCRIPTION
**Pull request by likeath**
Hello!
This commit provides `--table-name` option to model generator as described in #823.

This is rework of #834 against `develop` branch.

### CODE REVIEW

**Comment by AlfonsoUceda** [comment]
@likeath thanks! I'd go for `--relation-name` @jodosha

**Comment by likeath** [comment]
@jodosha @AlfonsoUceda done, now it's `relation-name`.
Should I squash commits?

**Comment by AlfonsoUceda** [comment]
@likeath don't worry, we can squash commit when merge the pull request

**Comment by jodosha** [comment]
@likeath Thank you. I'm gonna merge it. There are still a few issues that I'm gonna fix afterwards. 👍

**Pull request merged**
