### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by szepeviktor**
Found few misspellings with `typos`

### CODE REVIEW

**Review by cllns — APPROVED** [review]

**Comment by timriley** [comment]
Thanks for these fixes, @szepeviktor, and sorry for the delay! Would you mind addressing the merge conflict? Once that's done we can merge this ASAP.

**Comment by szepeviktor** [comment]
As you wish 🍏

**Review by timriley — APPROVED** [review]

**Comment by timriley** [comment]
Thanks again!

**Comment by szepeviktor** [comment]
Glad to contribute.

**Pull request merged**
