### PR TITLE
WIP: Report rendering errors to exception notification services

### PR DESCRIPTION
**Pull request by karimmtarek**
A potential fix for #528 
All I've done so far is applying this [code spike](https://github.com/hanami/hanami/commit/4c1b6e1024756f29d3c9c9207a99fd55a3c41bd0)
Please review and advise, thanks.

### CODE REVIEW

**Comment by jodosha** [comment]
@karimmtarek Hi and thanks for this fix. Can you please provide tests for this?

**Comment by karimmtarek** [comment]
@jodosha sure, I'll give it a shot and let you know :)

**Comment by karimmtarek** [comment]
@jodosha do we have a similar test case somewhere? I'm not sure what to test and where to put the test 😞

**Comment by akhramov** [comment]
@karimmtarek tests do not pass due to #599. You should remove [#successful?](https://github.com/karimmtarek/hanami/blob/fee309b5808af2587f43dd5790258d240a1d31e7/lib/hanami/rendering_policy.rb#L44) check.

**Comment by karimmtarek** [comment]
@akhramov done! thanks for the tip 👍

**Comment by karimmtarek** [comment]
@jodosha how does this look to you :)?
Please put in mind @akhramov comment:

> This commit introduces test cases for previously created error-handling
spike. The interesting part is that controller exception handler does
not re-raise exception while aforementioned spike does. This might bring
some inconsistency.

**Comment by jodosha** [comment]
@karimmtarek @akhramov This looks good. Thank you!

**Pull request merged**
