### PR TITLE
Fix: Correct order of setup commands in README

### PR DESCRIPTION
**Pull request by SusanGithaigaN**
Reordered the commands to ensure proper setup sequence for Hanami application.

### CODE REVIEW

**Comment by timriley** [comment]
Hi @SusanGithaigaN, thanks for this. I think the current order of commands is correct, however. If you can share specific errors that you see from following these commands, I'd be interested to see.

**Comment by SusanGithaigaN** [comment]
This is the error I am getting(check attached image):
The git source https://github.com/dry-rb/dry-inflector.git is not yet checked out. Please run `bundle install` before trying to start your application


Screenshot 2024-06-05 155307

**Comment by SusanGithaigaN** [comment]
> This is the error I am getting(check attached image): The git source https://github.com/dry-rb/dry-inflector.git is not yet checked out. Please run `bundle install` before trying to start your application
> 
> Screenshot 2024-06-05 155307

However, running `bundle install` before `hanami new bookshelf` solves the issue for me(see screenshot below): 

Screenshot 2024-06-05 155946

After that, I can successfully create a new bookshelf and run my server(see screenshot below): 
image

**Comment by timriley** [comment]
@SusanGithaigaN it looks like you're trying to run the `hanami` CLI command from _inside a checkout of the hanami/hanami repo_, is this right?

Can you please try doing the following in a completely new directory?

```
cd ~
mkdir testing_for_issue_1414
cd testing_for_issue_1414
gem install hanami
hanami new bookshelf
cat bookshelf/Gemfile
```

**Pull request closed without merging**
