### PR TITLE
capture_io for code reloading message

### PR DESCRIPTION
**Pull request by cllns**
Also add assertion to make sure that message is correct

Before:

```bash
$ ruby -Ilib:test test/commands/server_test.rb
Run options: --seed 48365

# Running:

................................Your platform doesn't support code reloading.
....

Finished in 0.104439s, 344.6980 runs/s, 402.1477 assertions/s.

36 runs, 42 assertions, 0 failures, 0 errors, 0 skips
```

After:
```bash
$ ruby -Ilib:test test/commands/server_test.rb
Run options: --seed 20962

# Running:

....................................

Finished in 0.048766s, 738.2183 runs/s, 902.2668 assertions/s.

36 runs, 44 assertions, 0 failures, 0 errors, 0 skips
```

I also added `@server.must_be_kind_of(Hanami::Server)` because  `@server.instance_variable_get(:@app).must_be_nil` doesn't really check anything on its own... you can set `@server = nil` and that `@server`'s `@app` is nil.

### CODE REVIEW

**Comment by cllns** [comment]
Also, what does everyone think about changing that `puts` to be `warn` instead? That'd output to STDERR instead of STDOUT.

**Comment by jodosha** [comment]
@cllns I really like this enhancement. Bravo! 👏 

> Also, what does everyone think about changing that puts to be warn instead? That'd output to STDERR instead of STDOUT.

Yes please 😉

**Comment by cllns** [comment]
done 👍

**Comment by joneslee85** [comment]
:+1:

**Comment by jodosha** [comment]
@cllns Thanks!

**Pull request merged**
