### PR TITLE
Adding new feature: --api option to app generator

### PR DESCRIPTION
**Pull request by Serhiy-Nazarov**
Quick generate API only application.
https://github.com/hanami/hanami/issues/673

TODO:
Auto add --skip-view option to action generator if app has --api option

### CODE REVIEW

**Comment by davydovanton** [comment]
any specs for this feature?

**Comment by davydovanton** [comment]
Agree with @cllns. Hanami-api gem will be awesome project. You can create json generator with presenters and with all useful logic and gems

**Comment by Serhiy-Nazarov** [comment]
hanami-api - it's a good idea. But I think in future API pattern must be main for hanami as part of the core.
just thought - maybe there is a way to extract the current generator into a gem hanami-app and create gem hanami-api...

**Comment by cllns** [comment]
Agree, as things separate into JSON API's, we maybe want to have Hanami itself be able to generate API's, without a plugin. But, first, I think `hanami-api` should be its own plugin, then we can integrate if if there's demand for it. :) 

How does that sound to you @Serhiy-Nazarov? Do you feel like you want to take that on?

**Comment by Serhiy-Nazarov** [comment]
@cllns 
as I said, I am a beginner with hanami :)
I want and can join in to work with more experienced hamani-developers

**Comment by cllns** [comment]
Closing this PR, since the appropriate place for this functionality is a Hanami plugin.

 @Serhiy-Nazarov If you want to work on this, I think you should see how far you can get creating a plugin, and then ask for help in the [Gitter chat](https://gitter.im/hanami/chat), and I'm sure someone will be able to help out :)

**Pull request closed without merging**
