### PR TITLE
Fix tests for app/container generators

### PR DESCRIPTION
**Pull request by joneslee85**
While working on other PR, I learn that tests are lying to me. 

cc @hanami/core-team

### CODE REVIEW

**Comment by AlfonsoUceda** [comment]
:+1: what do you think to squash commits?

**Comment by joneslee85** [comment]
yeah, I'll squash it

**Comment by joneslee85** [comment]
@AlfonsoUceda done

**Comment by AlfonsoUceda** [comment]
:+1:

**Pull request merged**
