### PR TITLE
Circle CI

### PR DESCRIPTION
**Pull request by jodosha**

### CODE REVIEW

**Comment by kaikuchn** [comment]
FYI you can verify that the circleci config file is valid using their [CLI](https://circleci.com/docs/2.0/local-cli/#installation) after installing it just run `circleci config validate` in the project directory.

**Comment by jodosha** [comment]
@kaikuchn Thanks for the input. Their CLI wasn't able to detect those problems 🤷 .

**Comment by timriley** [comment]
@jodosha I thought we were moving towards GitHub actions everywhere, what's your thinking with adding Circle here?

**Comment by jodosha** [comment]
@timriley I was trying to use something that I already know, to make this build to pass again. Given CI build for `master` became flaky, I was trying more CI systems to see which one passes. 🤷‍♂️

**Comment by jodosha** [comment]
Closing in favor of https://github.com/hanami/hanami/pull/1090

**Pull request closed without merging**
