### PR TITLE
Scope constant check to application module

### PR DESCRIPTION
**Pull request by pascalbetz**
Fixes https://github.com/hanami/hanami/issues/631#issuecomment-238513397

All specs pass. Additionally tested manually.

### CODE REVIEW

**Comment by jodosha** [comment]
@pascalbetz Thanks for this PR! Can you please add a constant in one of the fixtures applications to prove that this proposed change, actually fixes the name clashing problem? Thanks!

**Comment by pascalbetz** [comment]
Good catch with the tests. The mere presence of a class ```Controller``` breaks hanami in some weird way. Investigating.

**Comment by pascalbetz** [comment]
I think one of the problems is https://github.com/hanami/utils/issues/151

**Comment by pascalbetz** [comment]
@jodosha 
What is the expected behavior when a ```Namespace::View``` is defined _but_ it is not a ```Hanami::View``` ?

For namespaced apps I think it's OK to fail. But if the user modifies ```view_pattern``` to be rooted in the top level namespace (```view_pattern       '%{controller}::%{action}'```) then its quite possible that a ```Object::View``` already exists.

WDYT?

**Comment by jodosha** [comment]
@pascalbetz I think it's safe to ignore "namespaced" apps. That is an legacy mechanism that I put in place in the early days of the project. The goal at that time was to make possible arbitrary project structure via that configuration.

Fast forward to today, there is no value to keep that feature, because nobody (myself included) cares about it. The idea is to cleanup it after 1.0.

**Comment by pascalbetz** [comment]
@jodosha 

Glad to hear! I immediately disliked the feature because I don't think a user should be able to change such an important concept.
Don't you think it should be removed before 1.0 because it is a breaking change?

About this PR: I'll make sure that the classes for the "conflict" test are not loaded in said scenario and update the PR.

**Comment by jodosha** [comment]
> Don't you think it should be removed before 1.0 because it is a breaking change?

I don't think anyone is using it.

**Comment by pascalbetz** [comment]
@jodosha I've added a test. Please review.

**Comment by jodosha** [comment]
@pascalbetz This looks good to me. Thanks! Once the CI will be green, I'll merge it. 😉

**Comment by pascalbetz** [comment]
CI better be green because "it works on my machine"©️  
😄

**Pull request merged**
