### PR TITLE
Change Lotus logo to Hanami logo

### PR DESCRIPTION
**Pull request by cllns**
Unfortunately the new image is much larger than the old one. I used 64 colors on the PNG to convert it
then did the same process as #403 

The image is 500 pixels wide, but with the image tag I change the width to 350, so we could reduce the size of the image. The down-side is that it'd look more blurry on Retina screens (it's going to look a little blurry anyway).

screen shot 2016-01-22 at 11 39 05

@jodosha

### CODE REVIEW

**Comment by cllns** [comment]
Size after TinyPNG, before Base64: 11233 bytes
Base64 size: 15002 bytes

I think the old one was like 2KB to 2.5KB

**Comment by davydovanton** [comment]
looks cool! :+1:

**Comment by artofhuman** [comment]
:+1:

**Comment by jodosha** [comment]
@cllns Thank you! :+1:

**Pull request merged**
