### PR TITLE
install bundler inside TravisCI

### PR DESCRIPTION
**Pull request by aderyabin**
Travis do not install `bundler` for JRuby by default, so let's help him.

### CODE REVIEW

**Comment by joneslee85** [comment]
@aderyabin can we do it just for JRuby?

**Comment by aderyabin** [comment]
@joneslee85 Done!

**Comment by joneslee85** [comment]
thanks @aderyabin

**Comment by jodosha** [comment]
@aderyabin @joneslee85 Thank you :+1:

**Pull request merged**
