### PR TITLE
Update logo in welcome page

### PR DESCRIPTION
**Pull request by davydovanton**
screenshot 2016-05-21 12 35 17

/cc @hanami/core-team

### CODE REVIEW

**Comment by jodosha** [comment]
@davydovanton Thank you. How did you generated the logo?

**Comment by davydovanton** [comment]
@jodosha it was base64 from logo based in site :)

**Comment by jodosha** [comment]
@davydovanton My question was, how did you generated the base64 ;)

**Comment by davydovanton** [comment]
@jodosha ohh 😅 
I used [this site](http://www.freeformatter.com/base64-encoder.html)

**Pull request merged**
