### PR TITLE
Update with_shotgun_spec.rb

### PR DESCRIPTION
**Pull request by fewtaeyeon**

### CODE REVIEW

**Comment by AlfonsoUceda** [comment]
Hi @fewtaeyeon why this change? Thanks

**Comment by cllns** [comment]
@AlfonsoUceda I guess just to make the spec cleaner, to keep consistent indentation.

This means that file has a bunch of leading spaces, which is not how it would ever be for users, so I don't think this is a good change.

Since we only use Ruby 2.3+, we could use squiggly heredoc `<<~` here, which strips the leading space from the output string.

We have 40 (at least) files with HEREDOCs https://github.com/hanami/hanami/search?utf8=✓&q=EOF&type= though, so if we do that, we should do it across the board.

**Comment by AlfonsoUceda** [comment]
@cllns I'd do that, I prefer change them all of them in one PR, that one file per PR, what do you think?

**Comment by fewtaeyeon** [comment]
Sorry, I just want it to look cleaner so I does that and I agree with you @cllns  @AlfonsoUceda .

Thank you for comment and correcting me.

**Comment by cllns** [comment]
@fewtaeyeon Do you want to submit a PR for changing all the HEREDOCS in this repo to be indented properly, with the squiggly heredoc? It's OK if not, just let us know :)

**Comment by AlfonsoUceda** [comment]
I'm going to close this PR, @fewtaeyeon please can you follow @cllns's suggestion?

**Comment by jodosha** [comment]
@fewtaeyeon If you're keen to, please update all the occurrences with @cllns suggestion. Thanks 👍

**Pull request closed without merging**
