### PR TITLE
Look for require of ../apps/.*/application instead of ../lib/.*

### LINKED ISSUE #882: `hanami generate app X` requires `require_relative '../lib/.*'` to be present in `config/environment.rb`
When I try to generate new app using `hanami generate app admin`, I get this
output

```plaintext
[wolf@devel dia]$ bundle exec hanami generate app admin
      create  apps/admin/application.rb
      create  apps/admin/config/routes.rb
      create  apps/admin/views/application_layout.rb
      create  apps/admin/templates/application.html.erb
      create  apps/admin/assets/favicon.ico
      create  apps/admin/controllers/.gitkeep
      create  apps/admin/assets/images/.gitkeep
      create  apps/admin/assets/javascripts/.gitkeep
      create  apps/admin/assets/stylesheets/.gitkeep
      create  spec/admin/features/.gitkeep
      create  spec/admin/controllers/.gitkeep
      create  spec/admin/views/application_layout_spec.rb
Cannot find `(?-mix:require_relative '\.\.\/lib\/.*')' inside `config/environment.rb'.
```

It's caused by following line in generate app command:

https://github.com/hanami/hanami/blob/master/lib/hanami/cli/commands/generate/app.rb#L194

Since the `require_relative '../lib/.*'` is not necessarily present when using
own ORM, I would propose replacing the line with

```ruby
files.inject_line_after(destination, /require_relative '\.\.\/apps\/.*\/application'/, content)
```

since that should be always present at least once.

### PR DESCRIPTION
**Pull request by graywolf**
Fixes #882

### CODE REVIEW

**Comment by graywolf** [comment]
I will give it a shot :)

**Comment by davydovanton** [comment]
hey, really nice PR. And I agree with @cllns about specs. I think you can find all necessary specs here: https://github.com/hanami/hanami/blob/master/spec/integration/cli/generate/app_spec.rb#L43-L44

**Comment by AlfonsoUceda** [comment]
@graywolf we need a spec for this, if you can add it, please ping us a I can try it ;)

**Comment by graywolf** [comment]
Sorry, RL's been a bit busy, will get to it tomorrow (I hope).

**Comment by graywolf** [comment]
Making me to do the spec was right call, it revealed issue with my code,
it should be fixed now.

I didn't really have to do anything as far the spec goes (only reorder two
lines), since it already was testing if this line is added correctly.



As a side node, I've got this error when running `./script/ci`, any idea
what I'm doing wrong?

	[wolf@devel hanami]$ ./script/ci 
	Cleaning up.. done
	Using rake 12.3.0
	Using public_suffix 3.0.1
	Using addressable 2.5.2
	Using ffi 1.9.18
	Using childprocess 0.8.0
	Using contracts 0.16.0
	Using builder 3.2.3
	Using backports 3.11.1
	Using cucumber-tag_expressions 1.1.1
	Using gherkin 5.0.0
	Using cucumber-core 3.1.0
	Using cucumber-expressions 5.0.13
	Using cucumber-wire 0.0.1
	Using diff-lcs 1.3
	Using multi_json 1.13.1
	Using multi_test 0.1.2
	Using cucumber 3.1.0
	Using rspec-support 3.7.1
	Using rspec-expectations 3.7.0
	Using thor 0.19.4
	Using aruba 0.14.3
	Using ast 2.4.0
	Using bond 0.5.1
	Using bundler 1.16.1
	Using byebug 10.0.0
	Using mini_mime 1.0.0
	Using mini_portile2 2.3.0
	Using nokogiri 1.8.2
	Using rack 2.0.4
	Using rack-test 0.8.2
	Using xpath 3.0.0
	Using capybara 2.17.0
	Using cliver 0.3.2
	Using coderay 1.1.2
	Using coffee-script-source 1.12.2
	Using execjs 2.7.0
	Using coffee-script 2.4.1
	Using concurrent-ruby 1.0.5
	Using json 2.1.0
	Using docile 1.1.5
	Using simplecov-html 0.10.2
	Using simplecov 0.14.1
	Using tins 1.16.3
	Using term-ansicolor 1.6.0
	Using coveralls 0.8.21
	Using dotenv 2.2.1
	Using dry-configurable 0.7.0
	Using dry-container 0.6.0
	Using dry-core 0.4.2
	Using dry-equalizer 0.2.0
	Using dry-initializer 1.4.1
	Using dry-logic 0.4.2
	Using inflecto 0.0.2
	Using dry-types 0.11.1
	Using ice_nine 0.11.2
	Using dry-struct 0.3.1
	Using dry-validation 0.11.0
	Using excon 0.60.0
	Using transproc 1.0.2
	Using hanami-utils 1.1.2 from https://github.com/hanami/utils.git (at 1.1.x@7f489fa)
	Using hanami-helpers 1.1.1 from https://github.com/hanami/helpers.git (at 1.1.x@395b27a)
	Using tilt 2.0.8
	Using hanami-assets 1.1.0 from https://github.com/hanami/assets.git (at 1.1.x@32823fa)
	Using hanami-cli 0.1.0 from https://github.com/hanami/cli.git (at 0.1.x@62630f8)
	Using hanami-controller 1.1.1 from https://github.com/hanami/controller.git (at 1.1.x@75ceb29)
	Using mail 2.7.0
	Using hanami-mailer 1.1.0 from https://github.com/hanami/mailer.git (at 1.1.x@2d1f716)
	Using url_mount 0.2.1
	Using http_router 0.11.2
	Using hanami-router 1.1.0 from https://github.com/hanami/router.git (at 1.1.x@ccb0775)
	Using hanami-validations 1.1.0 from https://github.com/hanami/validations.git (at 1.1.x@7eea9b1)
	Using hanami-view 1.1.0 from https://github.com/hanami/view.git (at 1.1.x@95b3ed1)
	Using hanami 1.1.0 from source at `.`
	Using parallel 1.12.1
	Using parser 2.4.0.2
	Using powerpack 0.1.1
	Using rainbow 2.2.2
	Using ruby-progressbar 1.9.0
	Using unicode-display_width 1.3.0
	Using rubocop 0.50.0
	Using hanami-devtools 0.1.0 from https://github.com/hanami/devtools.git (at master@1ca1d43)
	Using rom-mapper 0.5.1
	Using rom 3.3.3
	Using rom-repository 1.4.0
	Using sequel 4.49.0
	Using rom-sql 1.3.5
	Using hanami-model 1.1.0 from https://github.com/hanami/model.git (at 1.1.x@4aaa7c6)
	Using i18n 0.9.3
	Using kgio 2.11.2
	Using libv8 3.16.14.19 (x86_64-linux)
	Using method_source 0.9.0
	Using websocket-extensions 0.1.3
	Using websocket-driver 0.7.0
	Using poltergeist 1.17.0
	Using pry 0.11.3
	Using puma 3.11.2
	Using raindrops 0.19.0
	Using rb-fsevent 0.10.2
	Using rb-inotify 0.9.10
	Using ref 2.0.0
	Using ripl 0.7.1
	Using rspec-core 3.7.1
	Using rspec-mocks 3.7.0
	Using rspec 3.7.0
	Using sass-listen 4.0.0
	Using sass 3.5.5
	Using shotgun 0.9.2
	Using sqlite3 1.3.13
	Using therubyracer 0.12.3
	Using unicorn 5.4.0
	Using yard 0.9.12
	Bundle complete! 35 Gemfile dependencies, 111 gems now installed.
	Bundled gems are installed into `./.vendor/bundle`
	Updating files in vendor/cache
	  * rake-12.3.0.gem
	  * public_suffix-3.0.1.gem
	  * addressable-2.5.2.gem
	  * ffi-1.9.18.gem
	  * childprocess-0.8.0.gem
	  * contracts-0.16.0.gem
	  * builder-3.2.3.gem
	  * backports-3.11.1.gem
	  * cucumber-tag_expressions-1.1.1.gem
	  * gherkin-5.0.0.gem
	  * cucumber-core-3.1.0.gem
	  * cucumber-expressions-5.0.13.gem
	  * cucumber-wire-0.0.1.gem
	  * diff-lcs-1.3.gem
	  * multi_json-1.13.1.gem
	  * multi_test-0.1.2.gem
	  * cucumber-3.1.0.gem
	  * rspec-support-3.7.1.gem
	  * rspec-expectations-3.7.0.gem
	  * thor-0.19.4.gem
	  * aruba-0.14.3.gem
	  * ast-2.4.0.gem
	  * bond-0.5.1.gem
	  * byebug-10.0.0.gem
	  * mini_mime-1.0.0.gem
	  * mini_portile2-2.3.0.gem
	  * nokogiri-1.8.2.gem
	  * rack-2.0.4.gem
	  * rack-test-0.8.2.gem
	  * xpath-3.0.0.gem
	  * capybara-2.17.0.gem
	  * cliver-0.3.2.gem
	  * coderay-1.1.2.gem
	  * coffee-script-source-1.12.2.gem
	  * execjs-2.7.0.gem
	  * coffee-script-2.4.1.gem
	  * concurrent-ruby-1.0.5.gem
	  * json-2.1.0.gem
	  * docile-1.1.5.gem
	  * simplecov-html-0.10.2.gem
	  * simplecov-0.14.1.gem
	  * tins-1.16.3.gem
	  * term-ansicolor-1.6.0.gem
	  * coveralls-0.8.21.gem
	  * dotenv-2.2.1.gem
	  * dry-configurable-0.7.0.gem
	  * dry-container-0.6.0.gem
	  * dry-core-0.4.2.gem
	  * dry-equalizer-0.2.0.gem
	  * dry-initializer-1.4.1.gem
	  * dry-logic-0.4.2.gem
	  * inflecto-0.0.2.gem
	  * dry-types-0.11.1.gem
	  * ice_nine-0.11.2.gem
	  * dry-struct-0.3.1.gem
	  * dry-validation-0.11.0.gem
	  * excon-0.60.0.gem
	  * transproc-1.0.2.gem
	  * tilt-2.0.8.gem
	  * mail-2.7.0.gem
	  * url_mount-0.2.1.gem
	  * http_router-0.11.2.gem
	  * parallel-1.12.1.gem
	  * parser-2.4.0.2.gem
	  * powerpack-0.1.1.gem
	  * rainbow-2.2.2.gem
	  * ruby-progressbar-1.9.0.gem
	  * unicode-display_width-1.3.0.gem
	  * rubocop-0.50.0.gem
	  * rom-mapper-0.5.1.gem
	  * rom-3.3.3.gem
	  * rom-repository-1.4.0.gem
	  * sequel-4.49.0.gem
	  * rom-sql-1.3.5.gem
	  * i18n-0.9.3.gem
	  * kgio-2.11.2.gem
	  * libv8-3.16.14.19-x86_64-linux.gem
	  * method_source-0.9.0.gem
	  * websocket-extensions-0.1.3.gem
	  * websocket-driver-0.7.0.gem
	  * poltergeist-1.17.0.gem
	  * pry-0.11.3.gem
	  * puma-3.11.2.gem
	  * raindrops-0.19.0.gem
	  * rb-fsevent-0.10.2.gem
	  * rb-inotify-0.9.10.gem
	  * ref-2.0.0.gem
	  * ripl-0.7.1.gem
	  * rspec-core-3.7.1.gem
	  * rspec-mocks-3.7.0.gem
	  * rspec-3.7.0.gem
	  * sass-listen-4.0.0.gem
	  * sass-3.5.5.gem
	  * shotgun-0.9.2.gem
	  * sqlite3-1.3.13.gem
	  * therubyracer-0.12.3.gem
	  * unicorn-5.4.0.gem
	  * yard-0.9.12.gem

	Installed hanami-utils-1.1.2.gem (from /home/wolf/devel/hanami/vendor/cache/utils-7f489fad55ca)
	Installed hanami-validations-1.1.0.gem (from /home/wolf/devel/hanami/vendor/cache/validations-7eea9b1ece4c)
	Installed hanami-router-1.1.0.gem (from /home/wolf/devel/hanami/vendor/cache/router-ccb0775a0318)
	Installed hanami-helpers-1.1.1.gem (from /home/wolf/devel/hanami/vendor/cache/helpers-395b27a22e0d)
	WARNING:  open-ended dependency on bundler (>= 0, development) is not recommended
	  if bundler is semantically versioned, use:
		add_development_dependency 'bundler', '~> 0'
	WARNING:  See http://guides.rubygems.org/specification-reference/ for help
	Installed hanami-model-1.1.0.gem (from /home/wolf/devel/hanami/vendor/cache/model-4aaa7c60d25f)
	Installed hanami-view-1.1.0.gem (from /home/wolf/devel/hanami/vendor/cache/view-95b3ed177a4e)
	Installed hanami-controller-1.1.1.gem (from /home/wolf/devel/hanami/vendor/cache/controller-75ceb29a3b9f)
	WARNING:  open-ended dependency on bundler (>= 0, development) is not recommended
	  if bundler is semantically versioned, use:
		add_development_dependency 'bundler', '~> 0'
	WARNING:  See http://guides.rubygems.org/specification-reference/ for help
	Installed hanami-mailer-1.1.0.gem (from /home/wolf/devel/hanami/vendor/cache/mailer-2d1f716417f9)
	WARNING:  open-ended dependency on bundler (>= 0, development) is not recommended
	  if bundler is semantically versioned, use:
		add_development_dependency 'bundler', '~> 0'
	WARNING:  See http://guides.rubygems.org/specification-reference/ for help
	Installed hanami-assets-1.1.0.gem (from /home/wolf/devel/hanami/vendor/cache/assets-32823facdebe)
	WARNING:  open-ended dependency on bundler (>= 0, development) is not recommended
	  if bundler is semantically versioned, use:
		add_development_dependency 'bundler', '~> 0'
	WARNING:  See http://guides.rubygems.org/specification-reference/ for help
	Installed hanami-cli-0.1.0.gem (from /home/wolf/devel/hanami/vendor/cache/cli-62630f85ead8)

	hanami 1.1.0 built to pkg/hanami-1.1.0.gem.
	Installed /home/wolf/devel/hanami/pkg/hanami-1.1.0.gem (from 3952ae58171985eaa16028d921dc601b7ed8420f)

	Generating Marshal quick index gemspecs for 0 gems

	Complete
	Generated Marshal quick index gemspecs: 0.000s
	Generating specs index
	Generated specs index: 0.000s
	Generating latest specs index
	Generated latest specs index: 0.000s
	Generating prerelease specs index
	Generated prerelease specs index: 0.000s
	Compressing indices
	Compressed indices: 0.000s

	/usr/bin/ruby -I/home/wolf/devel/hanami/.vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/lib:/home/wolf/devel/hanami/.vendor/bundle/ruby/2.5.0/gems/rspec-support-3.7.1/lib /home/wolf/devel/hanami/.vendor/bundle/ruby/2.5.0/gems/rspec-core-3.7.1/exe/rspec spec/unit/application_configuration_spec.rb spec/unit/application_spec.rb spec/unit/env_spec.rb spec/unit/environment_spec.rb spec/unit/version_spec.rb

	Randomized with seed 52676
	.......*.......................................*

	Pending: (Failures listed here are expected and do not affect your suite's status)

	  1) Hanami::ApplicationConfiguration#port when already configured in the general configuration and forced by env var returns the one from the env var
		 # Temporarily skipped with xit
		 # ./spec/unit/application_configuration_spec.rb:85

	  2) Hanami::Application.configuration= raises error if assign configuration more than once
		 # Temporarily skipped with xit
		 # ./spec/unit/application_spec.rb:28


	Finished in 0.02328 seconds (files took 0.95265 seconds to load)
	48 examples, 0 failures, 2 pending

	Randomized with seed 52676




	Running: /home/wolf/devel/hanami/spec/isolation/application/configure_spec.rb

	Randomized with seed 35216

	Hanami::Application
	  .configure
		without environment
		  setups general settings
		with environment
		  allows to setup multiple times per env settings
		  setups per env settings

	Finished in 0.00591 seconds (files took 0.93523 seconds to load)
	3 examples, 0 failures

	Randomized with seed 35216




	Running: /home/wolf/devel/hanami/spec/isolation/components/all/component_spec.rb

	Randomized with seed 13832

	Components: all
	  loads all (FAILED - 1)

	Failures:

	  1) Components: all loads all
		 Failure/Error: raise ArgumentError.new("Component not resolved: `#{name}'.\nResolved components are: #{@_resolved.keys.join(', ')}")
		 
		 ArgumentError:
		   Component not resolved: `admin'.
		   Resolved components are: environment, logger, code, code_reloading, mailer.configuration, mailer, model.bundled, model.configuration, model.sql, model, web.configuration, web.controller, web.view, web.assets, web.routes, web, apps, finalizers.initializers, finalizers, all
		 # ./lib/hanami/components.rb:129:in `block in []'
		 # ./.vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/map.rb:122:in `fetch'
		 # ./lib/hanami/components.rb:128:in `[]'
		 # ./spec/isolation/components/all/component_spec.rb:20:in `block (3 levels) in <top (required)>'
		 # ./spec/support/with_project.rb:20:in `block (2 levels) in with_project'
		 # ./spec/support/within_project_directory.rb:21:in `block in within_project_directory'
		 # ./.vendor/bundle/ruby/2.5.0/gems/aruba-0.14.3/lib/aruba/platforms/local_environment.rb:22:in `call'
		 # ./.vendor/bundle/ruby/2.5.0/gems/aruba-0.14.3/lib/aruba/platforms/unix_platform.rb:78:in `with_environment'
		 # ./.vendor/bundle/ruby/2.5.0/gems/aruba-0.14.3/lib/aruba/api/core.rb:64:in `cd'
		 # ./spec/support/within_project_directory.rb:11:in `within_project_directory'
		 # ./spec/support/with_project.rb:17:in `block in with_project'
		 # ./spec/support/with_tmp_directory.rb:11:in `block in with_tmp_directory'
		 # ./spec/support/with_directory.rb:13:in `with_directory'
		 # ./spec/support/with_tmp_directory.rb:10:in `with_tmp_directory'
		 # ./spec/support/with_project.rb:14:in `with_project'
		 # ./spec/isolation/components/all/component_spec.rb:3:in `block (2 levels) in <top (required)>'

	Finished in 1.4 seconds (files took 0.91028 seconds to load)
	1 example, 1 failure

	Failed examples:

	rspec ./spec/isolation/components/all/component_spec.rb:2 # Components: all loads all

	Randomized with seed 13832

	Failing test: /home/wolf/devel/hanami/spec/isolation/components/all/component_spec.rb
	Cleaning up.. done

**Comment by graywolf** [comment]
Also thinking about it, this PR should be against `develop`, not `master`, correct?

**Comment by cllns** [comment]
👍  Yup, it should be against `develop`, just changed it to that.

**Comment by graywolf** [comment]
Hm anything missing then or ready to merge?

**Comment by graywolf** [comment]
Sorry, bit busy will get to it over a weekend.

**Comment by graywolf** [comment]
I think I need some advice about proper process here. In order to implement this, I need to add new function to `Hanami::Utils`. Once I get PR merge into there, will this repository use newest from git? Or is in spec used newest stable release?

Not sure how to proceed... Please advice! ^_^

**Comment by jodosha** [comment]
@graywolf Hi, which new function do you need? Would you like to discuss it here? Thanks.

**Comment by jodosha** [comment]
@graywolf Please implement in `hanami-utils` on the `master` branch. We'll rebase this PR as well to `master`, given it's a fix, not a feature.

So this can be included in v1.2.1.

**Comment by graywolf** [comment]
So now when my change into `hanami-utils` was merge, how do I get `hanami` to use that version so I can develop on top of it? :)

**Comment by graywolf** [comment]
The bundler seems to be using `Using hanami-utils 1.3.0.beta1 from https://github.com/hanami/utils.git (at develop@495bb17)` but I don't see my changes in develop (when I inspect develop branch the `https://github.com/hanami/utils/blob/develop/lib/hanami/utils/files.rb` file does not contain my new methods). How can I force bundler to use master branch instead of develop?

**Comment by Argonus** [comment]
@jodosha Could you take a look?

**Comment by graywolf** [comment]
@jodosha I've tried that (I've even made a test case for that) and it seems to work... what am I missing?

**Pull request merged**
