### PR TITLE
Create format option for logger

### PR DESCRIPTION
**Pull request by davydovanton**
Reference to https://github.com/hanami/utils/pull/122

/cc @jodosha

### CODE REVIEW

**Comment by jodosha** [comment]
@davydovanton Thanks for this PR, but we shouldn't hardcode that logic. We probably want a per env setting in configuration blocks.

```ruby
module Web
  class Application < Hanami::Application
    configure do
      logging.formatter :json
    end
  end
end
```

**Comment by davydovanton** [comment]
@jodosha good point, I like it 👍

**Comment by davydovanton** [comment]
@jodosha done :tada

**Comment by joneslee85** [comment]
👍 @davydovanton

**Comment by jodosha** [comment]
@davydovanton This is almost done 😉 .

My suggestion is to generate [new applications](https://github.com/hanami/hanami/blob/fc4abbe5232df59cf20dd6608920434b57bc1dfd/lib/hanami/generators/app/application.rb.tt#L295) with this setting.

```ruby
configure :development do
  # Logger format. It defaults to DEFAULT
  # logger.format :default
end

configure :production do
  logger.format :json
end
```

**Comment by davydovanton** [comment]
yep, I liked it 👍

**Comment by jodosha** [comment]
@davydovanton Thank you! Just merged.

**Pull request merged**
