### PR TITLE
Generate new projects with config/boot.rb

### LINKED ISSUE #695: config/environment.rb not requiring initializers nor files in load paths
While setting up hanami + sidekiq, I came across two hurdles:
+ requiring `config/environment.rb` does not load initializers (which may or may not be the right thing to do, but since sidekiq does not boot the app, but simply requires that file, it forces one to require the sidekiq config directly from `config/environment`)
+ requiring `config/environment.rb` does not load files in the load paths declared within apps.

@jodosha Any thoughts on this?

### PR DESCRIPTION
**Pull request by jodosha**
Closes #695 

---

/cc @beauby @hanami/issues @hanami/ecosystem for review. 👍

### CODE REVIEW

**Comment by AlfonsoUceda** [comment]
You were quick haha, LGTM but I think someone using sidekiq could try this.

**Comment by jodosha** [comment]
@AlfonsoUceda This was already on my list. 😉 

We already had feedback from devs using Sidekiq when we were suggesting this patch.

@davydovanton Can you please confirm too? Thanks.

**Comment by jodosha** [comment]
@davydovanton Something like?

**Comment by davydovanton** [comment]
@jodosha maybe something like this?
```
# you can use this file for boot hanami apps in other services like sidekiq, etc
```

**Comment by jodosha** [comment]
@davydovanton I'd go for documenting it. By the time that you discover that file, you already figured out. 😉

**Pull request merged**
