### PR TITLE
Integration tools

### PR DESCRIPTION
**Pull request by jodosha**
Extracted local RSpec helpers into `hanami-devtools` and use them from the gem.

### CODE REVIEW

**Comment by jodosha** [comment]
@davydovanton https://github.com/hanami/webconsole/pull/1 and https://github.com/jodosha/hanami-reloader/pull/6 are using new `hanami-devtools` version.

**Comment by jodosha** [comment]
@davydovanton Are you talking about a Hanami project like `bookshelf` (aka a final product built with Hanami)? If so, there is no need. These tools are designed to build Hanami and Hanami plugins, not projects.

**Comment by davydovanton** [comment]
@jodosha no, I mean something like: "as a hanami plugin developer, I can take `hanami-devtools` repo and use some integration matchers for testing my hanami plugin/hanami project/etc" :)

**Comment by jodosha** [comment]
@davydovanton I see. Well, in that case you have two examples linked above 😉 .

**Pull request merged**
