### PR TITLE
WIP: Add minimal viable hanami app template

### PR DESCRIPTION
**Pull request by jarosluv**
Hi folks!

This is the trying to implement minimal viable Hanami app template for reproducing bug in bug reports. The main discussion is here #786.

For now we need to decide:
1. Which repository to choose for template
1. What template we need – one for all or several for each context (model, controller, etc)
1. How to fix all errors in my example (if you try to uncomment code in template, you get error)

All your replies are very important.

### CODE REVIEW

**Comment by AlfonsoUceda** [comment]
@jarosluv thanks for this ;) I think we need it.

Answering to your questions:
> 1. Which repository to choose for template

I think we should support the following repositories: hanami, router, controller, model, view, assets and mailer.

> 2. What template we need – one for all or several for each context (model, controller, etc)

In hanami repo I think we can go with a full template, loading all the app.

> 3. How to fix all errors in my example (if you try to uncomment code in template, you get error)

I haven't tried it but don't worry because we'll fix it, I'll try when I have time.

**Comment by jarosluv** [comment]
@jodosha 

I get the same error with `bundler-1.16.0.pre.2`, but with stable version of bundler `bundler-1.15.4` all is well. Please, try it with downgraded version of bundler.

So, I'm trying to figure out where the error comes from with the latest bundler version.

**Comment by jarosluv** [comment]
@jodosha 

Please, try to enter `templates` directory before:
```bash
> cd templates
> ruby minimal_hanami_app.rb
```

**Comment by jodosha** [comment]
@davydovanton I assigned this to you. Please coordinate with @jarosluv and decide if change this PR or close it. Thank you all.

**Comment by jodosha** [comment]
After a quick conversation with @davydovanton we decided to pull out these kind of templates out from the main repository.

@jarosluv Thanks for this contribution. I'm gonna close this PR.

**Comment by davydovanton** [comment]
@jarosluv also, could you open a PR to playbook repository instead `hanami/hanami`?
https://github.com/hanami/playbook/tree/master/development/bug_templates

**Comment by waiting-for-dev** [comment]
[console needs a "reload" command](https://trello.com/c/xolbnrfv/166-console-needs-a-reload-command)

**Pull request closed without merging**
